# For migration.

version: "3"

name: defi-migration

services:
  lending-bootstrap-deployer-migrated:
    extends:
      file: docker-compose.base.yml
      service: lending-bootstrap-deployer
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-bootstrap-deployer:${TAG:-latest}
    environment:
      DEPLOYER_CONFIG_FILE: /config/$NETWORK/runtime/lending-bootstrap-deployer-migrated.yaml

  lending-db:
    extends:
      file: docker-compose.base.yml
      service: lending-db

  lending-index:
    extends:
      file: docker-compose.base.yml
      service: lending-index
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-index:${TAG:-latest}
    depends_on:
      lending-db:
        condition: service_healthy

  lending-api:
    extends:
      file: docker-compose.base.yml
      service: lending-api
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-api:${TAG:-latest}
    depends_on:
      lending-index:
        condition: service_started

  lending-migration:
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-migration:${TAG:-latest}
    depends_on:
      lending-api:
        condition: service_started
    volumes:
      - cardano-node-socket:/ipc
    environment:
      API_URL: http://lending-api:3000
      DB_CONNECTION_STRING: postgres://lending-user:lending-password@lending-db:5432/lending-dev
      MIGRATION_OPERATOR_SIGNING_KEY_FILE: /run/secrets/migration_operator_signing_key_file
      CONTRACT_EXPORTER_CONFIG_FILE: /config/$NETWORK/lending-contracts-exporter.yaml
      MIGRATION_CONFIG_FILE: /config/$NETWORK/runtime/lending-migration.yaml
      SCRIPT_DIR: /exported-contracts/$NETWORK/
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
      GHCRTS: -N # Consider to enable this on deployment
    secrets:
      - migration_operator_signing_key_file
    configs:
      - source: runtime-config
        target: /config/$NETWORK/runtime

volumes:
  lending-db:
  cardano-node-socket:
    name: "${CARDANO_NODE_SOCKET_VOLUME}"
    external: true

secrets:
  deployer_signing_key_file:
    file: ../secrets/$NETWORK/deployer.xsk
  migration_operator_signing_key_file:
    file: ../secrets/$NETWORK/migration_operator.xsk

configs:
  runtime-config:
    file: ../config/$NETWORK/runtime
