# For local development and integration testing of the code base.

version: "3"

name: defi-local

services:
  lending-private-testnet:
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-private-testnet:${TAG:-latest}
    ports:
      - "8888:8888"
    environment:
      # For `cardano-cli` inside the Docker container.
      CARDANO_NODE_SOCKET_PATH: /private-testnet/example/node.socket
      # GHCRTS: -N # Consider to enable this on deployment
    volumes:
      - cardano-node-socket:/private-testnet/example
    healthcheck:
      test: ["CMD", "cardano-cli", "query", "tip", "--testnet-magic", "42"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 20s

  private-testnet-deployer-funding:
    image: 342832411065.dkr.ecr.eu-west-1.amazonaws.com/lending-private-testnet:${TAG:-latest}
    environment:
      # For `cardano-cli` inside the Docker container.
      CARDANO_NODE_SOCKET_PATH: /private-testnet/example/node.socket
      # GHCRTS: -N # Consider to enable this on deployment
    volumes:
      - cardano-node-socket:/private-testnet/example
    depends_on:
      lending-private-testnet:
        condition: service_healthy
    entrypoint: "/bin/bash -c"
    # UTXOs for
    # - Pool script deployment
    # - Account script deployment
    # - Other scripts deployment
    # - Collateral
    # - Root for manager
    # - Root for oracle
    # - Root for pool
    # - Root for manager operator NFT
    # - Root for oracle operator NFT
    # - Root for migration operator NFT
    # - Root for pool operator NFT
    # - Manager operator funding
    # - Oracle operator funding
    # - Migration operator funding
    # - Pool operator funding
    # - Batcher funding
    # - Test Ada faucet funding
    # - Root for deploying new Pool and AccountAuthToken script
    # - Root for deploying new Account and Manager script
    command:
      - ./fund-wallet.sh \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+60000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+70000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+70000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+5000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+8000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+6000000 \
        addr_test1vrc2jk3llu7lcr44558taqlx0hma5asvhkrut5vad3dvhpql4646u+50000000 \
        addr_test1vzsc4lza3ku55y9xp4vjmvq2fqqzsuu7x2np62z0mq6rrds9zjsz9+50000000 \
        addr_test1vpashx7spwaejk2qxafglrygrs7qcm4h06gurfe7nz77y9skx9kxp+50000000 \
        addr_test1vpyepvx93ktm4vjeztwg83v8vd3x2tjzkc37zgapm6e4xaq0kw9a7+50000000 \
        addr_test1vr4azw9kxtlrue3gtgm2ux4jd0dmcghje3ua033vz3kr6gsx9e665+50000000000 \
        addr_test1vquqzvx3gkmayjy2ksf69usadpdws5ggeh0evq2wh59lj0gjq76dw+200000000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+70000000 \
        addr_test1vz3dv63dzyuf2xzzp8r44evlrvzwvhvln7sk9g93tc4436snms60x+70000000

  lending-bootstrap-deployer:
    extends:
      file: docker-compose.base.yml
      service: lending-bootstrap-deployer
    depends_on:
      private-testnet-deployer-funding:
        condition: service_completed_successfully

  lending-bootstrap-initializer:
    extends:
      file: docker-compose.base.yml
      service: lending-bootstrap-initializer
    depends_on:
      lending-bootstrap-deployer:
        condition: service_completed_successfully

  lending-db:
    extends:
      file: docker-compose.base.yml
      service: lending-db

  lending-index:
    extends:
      file: docker-compose.base.yml
      service: lending-index
    depends_on:
      lending-private-testnet:
        condition: service_healthy
      lending-db:
        condition: service_healthy

  lending-api:
    extends:
      file: docker-compose.base.yml
      service: lending-api
    depends_on:
      lending-index:
        condition: service_started

  lending-api-docs:
    extends:
      file: docker-compose.base.yml
      service: lending-api-docs

  lending-services:
    extends:
      file: docker-compose.base.yml
      service: lending-services
    depends_on:
      lending-index:
        condition: service_started

  lending-oracle-service:
    extends:
      file: docker-compose.base.yml
      service: lending-oracle-service
    depends_on:
      lending-index:
        condition: service_started

  lending-tests:
    extends:
      file: docker-compose.base.yml
      service: lending-tests
    depends_on:
      lending-api:
        condition: service_started
      lending-services:
        condition: service_started
      lending-faucet:
        condition: service_started
      lending-mock-api:
        condition: service_started
      lending-oracle-service:
        condition: service_started
      private-testnet-deployer-funding:
        condition: service_completed_successfully

  lending-faucet:
    extends:
      file: docker-compose.base.yml
      service: lending-faucet
    depends_on:
      private-testnet-deployer-funding:
        condition: service_completed_successfully

  lending-mock-api:
    extends:
      file: docker-compose.base.yml
      service: lending-mock-api

  lending-liquidation-bot-liquidate:
    extends:
      file: docker-compose.base.yml
      service: lending-liquidation-bot-liquidate
    depends_on:
      lending-index:
        condition: service_started

  lending-liquidation-bot-close-account:
    extends:
      file: docker-compose.base.yml
      service: lending-liquidation-bot-close-account
volumes:
  lending-db:
  cardano-node-socket:

secrets:
  deployer_signing_key_file:
    file: ../secrets/$NETWORK/deployer.xsk
  manager_operator_signing_key_file:
    file: ../secrets/$NETWORK/manager_operator.xsk
  oracle_operator_signing_key_file:
    file: ../secrets/$NETWORK/oracle_operator.xsk
  pool_operator_signing_key_file:
    file: ../secrets/$NETWORK/pool_operator.xsk
  batcher_signing_key_file:
    file: ../secrets/$NETWORK/batcher.xsk
  faucet_signing_key_file:
    file: ../secrets/$NETWORK/faucet.xsk
  coin-market-cap-api-key-file:
    file: ../secrets/$NETWORK/cmc-api
  migration_operator_signing_key_file:
    file: ../secrets/$NETWORK/migration_operator.xsk
  liquidator_signing_key_file:
    file: ../secrets/$NETWORK/liquidator.xsk
  stake_signing_key_file:
    file: ../secrets/$NETWORK/stake.xsk

configs:
  runtime-config:
    file: ../config/$NETWORK/runtime
  lending-functional-tests:
    file: ../resources/functional-tests
